// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetInfo.dal;

namespace ProjetInfo.Migrations
{
    [DbContext(typeof(institutionContext))]
    [Migration("20201106133614_Migrations2")]
    partial class Migrations2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetInfo.dal.entities.ActivityCategory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("exclusive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("institutionid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("owner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("required")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("institutionid");

                    b.ToTable("ActivityCategory");
                });

            modelBuilder.Entity("ProjetInfo.dal.entities.institution", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("institutionid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("parentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("institutionid");

                    b.ToTable("institutions");
                });

            modelBuilder.Entity("ProjetInfo.dal.entities.ActivityCategory", b =>
                {
                    b.HasOne("ProjetInfo.dal.entities.institution", null)
                        .WithMany("activityCategories")
                        .HasForeignKey("institutionid");
                });

            modelBuilder.Entity("ProjetInfo.dal.entities.institution", b =>
                {
                    b.HasOne("ProjetInfo.dal.entities.institution", null)
                        .WithMany("children")
                        .HasForeignKey("institutionid");
                });
#pragma warning restore 612, 618
        }
    }
}
